[package]
name = "native_program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "~1.17.12"

[lib]
name = "native_program"
crate-type = ["cdylib", "lib"]
