[package]
name = "native_program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = { version = "=1.18.17", default-features = false }


[profile.release]
lto = true


[lib]
name = "native_program"
crate-type = ["cdylib", "lib"]
